import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { ProjectRegistryStore } from "../projects/project-registry";
import { TopologyService } from "../projects/project-topology";
import { OwnershipVerifier } from "../projects/ownership";
import { WorkflowStore } from "../workflows/workflow-store";
import { WorkflowEngine } from "../workflows/workflow-engine";
import { isTerminal, transition } from "../workflows/workflow-schema";
import { classifyCodexError } from "../codex/codex-error";
import { WorkflowRunner } from "../workflows/workflow-runner";
import { parsePorcelainZ } from "../projects/ownership";

async function fixture() { const root = await mkdtemp(path.join(os.tmpdir(), "orchestrator-")); await Promise.all([mkdir(path.join(root,"api")), mkdir(path.join(root,"web")), mkdir(path.join(root,"shared"))]); return root; }
function topology(root: string) { return { version: 1 as const, workspaceRoot: root, repositories: [ { id:"api", root:path.join(root,"api"), metadata:{}, ownership:[{pattern:"src/**",readableBy:["architect","backend"],writableBy:["backend"],architectControlled:false}] }, { id:"web", root:path.join(root,"web"), metadata:{}, ownership:[{pattern:"app/**",readableBy:["architect","frontend"],writableBy:["frontend"],architectControlled:false}] }, { id:"shared", root:path.join(root,"shared"), metadata:{}, ownership:[{pattern:"**",readableBy:["architect","backend","frontend"],writableBy:[],architectControlled:true}] } ], agentWorkspaces:{architect:{cwd:root},backend:{repositoryId:"api"},frontend:{repositoryId:"web"}} }; }
const assignment = { type:"TASK_ASSIGNMENT" as const, taskId:"t", assignedTo:"frontend" as const, title:"x", objective:"x", context:"", requirements:[], acceptanceCriteria:[], allowedPaths:["app/**"], forbiddenPaths:[], validationCommands:[], notes:[] };
const report = { type:"TASK_REPORT" as const, taskId:"t", agent:"frontend" as const, status:"READY_FOR_REVIEW" as const, summary:"x", filesChanged:["web:app/view.tsx"], testsChanged:[], validations:[], risks:[], blockers:[], notes:[] };

test("legacy registry migrates to a versioned topology without changing IDs", async () => { const root=await fixture(); await mkdir(path.join(root,"legacy")); await mkdir(path.join(root,".orchestrator")); await writeFile(path.join(root,".orchestrator","projects.json"), JSON.stringify({projects:{legacy:{id:"legacy",name:"Legacy",root:path.join(root,"legacy"),createdAt:"2020-01-01T00:00:00.000Z"}}})); const project=await new ProjectRegistryStore(root).getProject("legacy"); assert.equal(project.id,"legacy"); assert.equal(project.topology.repositories[0]?.root,path.join(root,"legacy")); assert.equal((await readFile(path.join(root,".orchestrator","projects.json"),"utf8")).includes('"version": 1'),true); });
test("multi-repo, hybrid ownership and Windows-style paths are deterministic", async () => { const root=await fixture(); const service=new TopologyService(topology(root)); assert.equal(service.workspaceFor("backend"),path.join(root,"api")); assert.equal(service.may("frontend","web","app/view.tsx","write"),true); assert.equal(service.may("frontend","api","src/x.ts","write"),false); assert.equal(service.isArchitectControlled("shared","thing.ts"),true); assert.throws(()=>service.resolveProjectPath("web","..\\api\\x.ts")); });
test("ownership verifier rejects developer writes outside assignment or topology", async () => { const root=await fixture(); const verifier=new OwnershipVerifier(new TopologyService(topology(root))); assert.equal(verifier.validateReport(assignment,report).ok,true); assert.equal(verifier.validateReport(assignment,{...report,filesChanged:["api:src/x.ts"]}).ok,false); });
test("workflow persistence, transitions, rate-limit pause and recovery are durable", async () => { const root=await fixture(); const store=new WorkflowStore(root); const engine=new WorkflowEngine(store); let workflow=await engine.create("project","request","workflow-a"); workflow=await engine.transition(workflow,"PLANNING","start"); workflow=await engine.pauseForError(workflow,new Error("HTTP 429 rate limit")); assert.equal(workflow.state,"PAUSED_RATE_LIMIT"); assert.equal((await store.recoverable("project")).length,1); assert.equal(isTerminal("PAUSED_RATE_LIMIT"),false); assert.equal(isTerminal("APPROVED"),true); assert.throws(()=>transition(workflow,"APPROVED","skip review")); assert.equal((await store.get("project","workflow-a")).rateLimit?.pausedAt !== undefined,true); });
test("error classifier distinguishes rate limits and failures", () => { assert.equal(classifyCodexError(new Error("quota exhausted")).kind,"RATE_LIMIT"); assert.equal(classifyCodexError(new Error("Codex App Server exited")).kind,"TRANSIENT_SERVER"); assert.equal(classifyCodexError(new Error("invalid request")).kind,"INVALID_REQUEST"); });
test("runner persists architect-developer-review loop including correction", async () => { const root=await fixture(); const store=new WorkflowStore(root); const engine=new WorkflowEngine(store); const verifier=new OwnershipVerifier(new TopologyService(topology(root))); let architectCalls=0; const architect={ sendStructured: async () => ({ data: architectCalls++ === 0 ? assignment : architectCalls === 2 ? { type:"REVIEW_RESULT", taskId:"t", reviewedAgent:"frontend", decision:"CHANGES_REQUESTED", summary:"fix", findings:[], requiredChanges:["fix"], validationRequired:[] } : { type:"REVIEW_RESULT", taskId:"t", reviewedAgent:"frontend", decision:"APPROVED", summary:"ok", findings:[], requiredChanges:[], validationRequired:[] } }) }; const router={ routeTask: async () => report }; const runner=new WorkflowRunner(engine,architect as never,router as never,verifier); let workflow=await engine.create("project","request","loop"); for(let i=0;i<8 && workflow.state!=="APPROVED";i++) workflow=await runner.run(workflow); assert.equal(workflow.state,"APPROVED"); assert.equal(workflow.reports.length,2); assert.equal(workflow.reviews.length,2); });
test("owner input, safe ids, architect control and porcelain rename are enforced", async () => { const root=await fixture(); const store=new WorkflowStore(root); const engine=new WorkflowEngine(store); let workflow=await engine.create("project","request","owner"); workflow=await engine.transition(workflow,"PLANNING","start"); workflow=await engine.requestOwnerInput(workflow,{type:"OWNER_INPUT_REQUIRED",reason:"choice",question:"which?",options:["a"]}); assert.equal(workflow.state,"WAITING_FOR_OWNER_INPUT"); workflow=await engine.answerOwnerInput(workflow,"a"); assert.equal(workflow.state,"PLANNING"); await assert.rejects(()=>engine.create("../bad","x","bad")); await assert.rejects(()=>engine.create("project","x","..\\bad")); const service=new TopologyService(topology(root)); const verifier=new OwnershipVerifier(service); assert.equal(verifier.validateReport(assignment,{...report,filesChanged:["shared:contract.ts"]}).ok,false); assert.deepEqual(parsePorcelainZ("R  new name\0old name\0?? spaced name\0"),["new name","old name","spaced name"]); });
