import type { OwnerInputRequest, ReviewResult, TaskAssignment, TaskReport } from "../protocol/team-messages";
import { classifyCodexError } from "../codex/codex-error";
import type { OwnershipValidation } from "../projects/ownership";
import { WorkflowStore } from "./workflow-store";
import { newWorkflow, transition, type Workflow, type WorkflowState } from "./workflow-schema";

export class WorkflowEngine {
  constructor(private readonly store: WorkflowStore) {}
  async create(projectId: string, request: string, id?: string) { const workflow = newWorkflow(projectId, request, id); await this.store.save(workflow); return workflow; }
  async transition(workflow: Workflow, next: WorkflowState, detail: string) { const changed = transition(workflow, next, detail); await this.store.save(changed); return changed; }
  async assign(workflow: Workflow, assignment: TaskAssignment) { const changed = transition({ ...workflow, assignment, assignedAgent: assignment.assignedTo, phase: "implementation", pendingAction: "implement", allowedScopes: assignment.allowedScopes ?? [], forbiddenScopes: assignment.forbiddenScopes ?? [] }, "ASSIGNED", "Architect assignment checkpointed"); await this.store.save(changed); return changed; }
  async report(workflow: Workflow, report: TaskReport, verification: OwnershipValidation) { const base = { ...workflow, reports: [...workflow.reports, report], ownershipValidations: [...workflow.ownershipValidations, { at: new Date().toISOString(), ok: verification.ok, violations: verification.violations, source: verification.source }] }; const next: WorkflowState = report.status === "READY_FOR_REVIEW" && verification.ok ? "READY_FOR_REVIEW" : "BLOCKED"; const changed = transition({ ...base, phase: next === "READY_FOR_REVIEW" ? "review" : "implementation", pendingAction: next === "READY_FOR_REVIEW" ? "review" : "owner-intervention" }, next, verification.ok ? "Developer report accepted after verification" : `Developer report rejected: ${verification.violations.join("; ")}`); await this.store.save(changed); return changed; }
  async review(workflow: Workflow, review: ReviewResult) { const next: WorkflowState = review.decision === "APPROVED" ? "APPROVED" : review.decision === "CHANGES_REQUESTED" ? "CHANGES_REQUESTED" : "BLOCKED"; const changed = transition({ ...workflow, reviews: [...workflow.reviews, review], retryCount: next === "CHANGES_REQUESTED" ? workflow.retryCount + 1 : workflow.retryCount, phase: next === "CHANGES_REQUESTED" ? "implementation" : "complete", pendingAction: next === "CHANGES_REQUESTED" ? "implement-correction" : null, baselines: next === "CHANGES_REQUESTED" ? [] : workflow.baselines }, next, `Architect review: ${review.decision}`); await this.store.save(changed); return changed; }
  async requestOwnerInput(workflow: Workflow, request: OwnerInputRequest) { const changed = transition({ ...workflow, ownerInput: { request, priorState: workflow.state, answer: null }, pendingAction: "owner-answer" }, "WAITING_FOR_OWNER_INPUT", "Architect requested owner input"); await this.store.save(changed); return changed; }
  async answerOwnerInput(workflow: Workflow, answer: string) { if (workflow.state !== "WAITING_FOR_OWNER_INPUT" || !workflow.ownerInput) throw new Error("Workflow is not waiting for owner input"); const prior = workflow.ownerInput.priorState; const changed = transition({ ...workflow, ownerInput: { ...workflow.ownerInput, answer }, pendingAction: prior === "REVIEWING" ? "review" : "plan" }, prior, "Owner answer persisted"); await this.store.save(changed); return changed; }
  async pauseForError(workflow: Workflow, error: unknown, rateLimitSnapshot: unknown = null) { const classified = classifyCodexError(error); const now = new Date(); if (classified.kind === "RATE_LIMIT") { const changed = transition({ ...workflow, lastError: classified.message, rateLimit: { pausedAt: now.toISOString(), retryAfter: null, snapshot: rateLimitSnapshot, previousState: workflow.state, pendingAction: workflow.pendingAction, agentRole: workflow.assignedAgent } }, "PAUSED_RATE_LIMIT", "RATE_LIMIT"); await this.store.save(changed); return changed; } if (classified.kind === "TRANSIENT_SERVER") { const attempts = (workflow.transient?.attempts ?? 0) + 1; const delay = Math.min(300_000, 1_000 * 2 ** Math.min(attempts, 8)); const changed = transition({ ...workflow, lastError: classified.message, transient: { previousState: workflow.state, attempts, retryAt: new Date(now.getTime() + delay).toISOString() } }, "PAUSED_TRANSIENT", "TRANSIENT_SERVER"); await this.store.save(changed); return changed; } const changed = transition({ ...workflow, lastError: classified.message }, "FAILED", classified.kind); await this.store.save(changed); return changed; }
  async updateRateLimit(workflow: Workflow, snapshot: unknown, nextCheckAt: string) { const changed = { ...workflow, rateLimit: { ...(workflow.rateLimit ?? { pausedAt: new Date().toISOString(), retryAfter: null, snapshot: null }), snapshot, nextCheckAt }, updatedAt: new Date().toISOString() }; await this.store.save(changed); return changed; }
  async resumePaused(workflow: Workflow) { const next = workflow.state === "PAUSED_TRANSIENT" ? workflow.transient?.previousState ?? "PLANNING" : workflow.state === "PAUSED_RATE_LIMIT" ? workflow.rateLimit?.previousState ?? (workflow.phase === "review" ? "READY_FOR_REVIEW" : workflow.assignment ? "ASSIGNED" : "PENDING") : workflow.state; return this.transition({ ...workflow, transient: null, rateLimit: workflow.state === "PAUSED_RATE_LIMIT" ? null : workflow.rateLimit }, next, "Resume persisted checkpoint"); }
  async recover(projectId: string) { return this.store.recoverable(projectId); }
}
