import { z } from "zod";
import { TaskAssignmentSchema, TaskReportSchema, ReviewResultSchema } from "../protocol/team-messages";

export const WorkflowStateSchema = z.enum(["PENDING", "PLANNING", "ASSIGNED", "IMPLEMENTING", "READY_FOR_REVIEW", "REVIEWING", "CHANGES_REQUESTED", "PAUSED_RATE_LIMIT", "PAUSED_MANUAL", "BLOCKED", "FAILED", "APPROVED", "CANCELLED"]);
export type WorkflowState = z.infer<typeof WorkflowStateSchema>;
export const TERMINAL_WORKFLOW_STATES: ReadonlySet<WorkflowState> = new Set(["APPROVED", "FAILED", "CANCELLED"]);
export const WorkflowSchema = z.object({
 version: z.literal(1), id: z.string().min(1), projectId: z.string().min(1), ownerRequest: z.string().min(1), state: WorkflowStateSchema, phase: z.string().min(1), assignedAgent: z.string().nullable(),
 assignment: TaskAssignmentSchema.nullable(), reports: z.array(TaskReportSchema), reviews: z.array(ReviewResultSchema), retryCount: z.number().int().nonnegative(), threadIds: z.record(z.string(), z.string()),
 pendingAction: z.string().nullable(), ownershipValidations: z.array(z.object({ at: z.string(), ok: z.boolean(), violations: z.array(z.string()), source: z.string() })), validationResults: z.array(z.string()), rateLimit: z.object({ pausedAt: z.string(), retryAfter: z.string().nullable(), snapshot: z.unknown().nullable() }).nullable(), lastError: z.string().nullable(), createdAt: z.string(), updatedAt: z.string(), checkpoints: z.array(z.object({ at: z.string(), action: z.string(), detail: z.string() })),
});
export type Workflow = z.infer<typeof WorkflowSchema>;
const allowed: Record<WorkflowState, readonly WorkflowState[]> = { PENDING:["PLANNING","CANCELLED","FAILED"], PLANNING:["ASSIGNED","PAUSED_RATE_LIMIT","BLOCKED","FAILED","CANCELLED"], ASSIGNED:["IMPLEMENTING","PAUSED_RATE_LIMIT","CANCELLED","FAILED"], IMPLEMENTING:["READY_FOR_REVIEW","BLOCKED","PAUSED_RATE_LIMIT","FAILED","CANCELLED"], READY_FOR_REVIEW:["REVIEWING","PAUSED_RATE_LIMIT","FAILED","CANCELLED"], REVIEWING:["APPROVED","CHANGES_REQUESTED","BLOCKED","PAUSED_RATE_LIMIT","FAILED","CANCELLED"], CHANGES_REQUESTED:["IMPLEMENTING","PAUSED_RATE_LIMIT","BLOCKED","FAILED","CANCELLED"], PAUSED_RATE_LIMIT:["PLANNING","ASSIGNED","IMPLEMENTING","READY_FOR_REVIEW","REVIEWING","PAUSED_MANUAL","CANCELLED","FAILED"], PAUSED_MANUAL:["PLANNING","ASSIGNED","IMPLEMENTING","READY_FOR_REVIEW","REVIEWING","CANCELLED","FAILED"], BLOCKED:["PLANNING","IMPLEMENTING","CANCELLED","FAILED"], FAILED:[], APPROVED:[], CANCELLED:[] };
export function isTerminal(state: WorkflowState) { return TERMINAL_WORKFLOW_STATES.has(state); }
export function transition(workflow: Workflow, state: WorkflowState, detail: string): Workflow { if (workflow.state !== state && !allowed[workflow.state].includes(state)) throw new Error(`Invalid workflow transition ${workflow.state} -> ${state}`); const now = new Date().toISOString(); return { ...workflow, state, updatedAt: now, checkpoints: [...workflow.checkpoints, { at: now, action: `${workflow.state}->${state}`, detail }] }; }
export function newWorkflow(projectId: string, ownerRequest: string, id?: string): Workflow { const workflowId: string = id ?? crypto.randomUUID(); const now = new Date().toISOString(); return { version: 1, id: workflowId, projectId, ownerRequest, state: "PENDING", phase: "planning", assignedAgent: null, assignment: null, reports: [], reviews: [], retryCount: 0, threadIds: {}, pendingAction: "plan", ownershipValidations: [], validationResults: [], rateLimit: null, lastError: null, createdAt: now, updatedAt: now, checkpoints: [{ at: now, action: "created", detail: "Workflow created" }] }; }
